main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('community/',views.community_page, name='community_page'),
    path('community/new/',views.community_new, name='community_new'),
    path('community/<int:post_id>/',views.community_detail, name="community_detail"),
    path('community/<int:post_id>/delete/',views.community_delete, name="community_delete"),
    path('community/<int:post_id>/comment/',views.community_comment, name="community_comment"),
    path('community/<int:post_id>/recomment/<int:comment_id>/',views.community_recomment, name="community_recomment"),
    path('community/<int:post_id>/recomment/<int:recomment_id>/delete/',views.recomment_delete, name="recomment_delete"),
    path('community/<int:post_id>/comment/<int:comment_id>/delete/',views.comment_delete, name="comment_delete"),
    path('community/<int:post_id>/comment/<int:comment_id>/edit/',views.comment_edit, name="comment_edit"),
    path('community/<int:post_id>/edit/',views.community_edit, name="community_edit"),
    path('notice/',views.notice_page, name='notice_page'),
    path('notice/new/',views.notice_new, name='notice_new'),
    path('notice/<int:post_id>/',views.notice_detail, name="notice_detail"),
    path('notice/<int:post_id>/delete/',views.notice_delete, name="notice_delete"),
    path('search/',views.search_pages, name='search_pages'),
    path('',views.home, name='home'),
    path('search/choice_mentor/<int:customer_id>',views.choice_mentor, name='choice_mentor'),
    path('cat1/',views.cat_1, name='cat_1'),
    path('cat2/',views.cat_2, name='cat_2'),
    path('cat3/',views.cat_3, name='cat_3'),
    path('cat3/search/<str:univers>/',views.search_page, name='search_page'),
]

menting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('home/', include('menteerequest.urls')),
    path('', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models
from accounts.models import CustomUser

class Post(models.Model):
    title = models.CharField(max_length=100)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE, null =True)
    content = models.TextField()
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    post = models.ForeignKey(Post, null = True, blank = True, on_delete=models.CASCADE)
    name = models.TextField()
    content = models.TextField()
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Recomment(models.Model):
    comment = models.ForeignKey(Comment, null = True, blank = True, on_delete=models.CASCADE)
    name2 = models.TextField(null =True)
    content = models.CharField(max_length=100)
    updated_at = models.DateTimeField(auto_now=True)

class Post2(models.Model):
    username= "STAFF"
    title = models.CharField(max_length=20, default = '')
    content = models.TextField()
    created_at =models.DateTimeField(auto_now_add=True, null = True)
    updated_at = models.DateTimeField(auto_now=True, null = True)

class Mentor(models.Model):    #선택한 멘토 정보를 요청창에 넘기기위한 새로운 모델
    username = models.CharField(max_length=20)
    email = models.CharField(max_length=20)
    university = models.CharField(max_length=50)


    

main/forms.py
from django import forms
from django.db.models import fields
from .models import Post, Comment, Post2, Mentor, Recomment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title','content']
        widgets = {
            'title': forms.Textarea(attrs={'rows':1, 'cols':165}),
            'content': forms.Textarea(attrs={'rows':4, 'cols':165}),
        }

class PostForm2(forms.ModelForm):   

    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows':5, 'cols':165}),
        }

class RecommentForm(forms.ModelForm):   

    class Meta:
        model = Recomment
        fields = ['content','comment']

class PostForm3(forms.ModelForm):

    class Meta:
        model = Post2
        fields = ['title','content']
        widgets = {
            'title': forms.Textarea(attrs={'rows':1, 'cols':165}),
            'content': forms.Textarea(attrs={'rows':4, 'cols':165}),
        }

class MentorForm(forms.ModelForm):

    class Meta:
        model = Mentor
        fields = ['username','email']

main/views.py
from django.forms.fields import CharField
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from .forms import PostForm, PostForm2, PostForm3, RecommentForm
from .models import Post, Comment, Post2, Mentor, Recomment
from accounts.forms import SignUpForm
from accounts.models import CustomUser
from django.contrib import messages




def home(request):
    return render(request, 'accounts/main2.html')

def community_page(request):

    post_list = Post.objects.all().order_by('-created_at')


    page = request.GET.get('page', '1')      #GET 방식으로 정보를 받아오는 데이터
    paginator = Paginator(post_list, 5)      #Paginator(분할될 객체, 페이지 당 담길 객체수)
    page_obj = paginator.get_page(page)      #페이지 번호를 받아 해당 페이지를 리턴 get_page 권장

    context = {
        'post_list': page_obj,
    }

    return render(request, 'main/community_page.html', context)

def community_new(request):
    if request.method == 'GET':
        form = PostForm()

    elif request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            post.user = request.user
            post.save()
            return redirect('community_page')

    return render(request, 'main/community_new.html',{
        'form': form,
    })

def community_edit(request, post_id):
    post = Post.objects.get(id=post_id)

    if request.method == 'GET':
        form = PostForm(instance=post)

    elif request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect('community_detail', post_id=post.id)

    return render(request, 'main/community_edit.html',{
        'form': form,
        'post': post,
    })

def community_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    post_form2 = PostForm2()
    recomment_form = RecommentForm()
    context = {
        'post': post,
        'post_form2': post_form2,
        'recomment_form': recomment_form,
    }

    return render(request, 'main/community_detail.html',context)

def community_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()   
    return redirect('community_page')

def community_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    commentt = PostForm2(request.POST)
    if commentt.is_valid():
        commentt = commentt.save(commit=False)
        commentt.post = get_object_or_404(Post, pk=post_id)
        commentt.name = request.user
        commentt.save()
    return redirect('community_detail', post_id=post.id)

def community_recomment(request, post_id, comment_id):
    post = get_object_or_404(Post, id=post_id)
    recomment = RecommentForm(request.POST)
    if recomment.is_valid():
        recomment = recomment.save(commit=False)
        recomment.comment = get_object_or_404(Comment, pk=comment_id)
        recomment.name2 = request.user
        recomment.save()
    return redirect('community_detail', post_id = post.id)

def comment_delete(request, post_id, comment_id):
    post = get_object_or_404(Post, id=post_id)
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()   
    return redirect('community_detail', post_id = post.id)

def recomment_delete(request, post_id, recomment_id):
    post = get_object_or_404(Post, id=post_id)
    recomment = get_object_or_404(Recomment, id=recomment_id)
    recomment.delete()   
    return redirect('community_detail', post_id = post.id)

def comment_edit(request, post_id, comment_id):
    post = Post.objects.get(id=post_id)
    comment = get_object_or_404(Comment, id=comment_id)

    if request.method == 'GET':
        form = PostForm2(instance=comment)

    elif request.method == 'POST':
        form = PostForm2(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save()
            return redirect('community_detail', post_id=post.id)

    return render(request, 'main/comment_edit.html',{
        'form': form,
        'comment': comment,
        'post':post,
    })

def notice_page(request):

    post2_list = Post2.objects.all().order_by('-created_at')


    page = request.GET.get('page', '1')      #GET 방식으로 정보를 받아오는 데이터
    paginator = Paginator(post2_list, 5)      #Paginator(분할될 객체, 페이지 당 담길 객체수)
    page_obj = paginator.get_page(page)      #페이지 번호를 받아 해당 페이지를 리턴 get_page 권장

    context = {
        'post2_list': page_obj,
    }
    return render(request, 'main/notice_page.html', context)

def notice_new(request):
    if request.method == 'GET':
        form = PostForm3()

    elif request.method == 'POST':
        form = PostForm3(request.POST)
        if form.is_valid():
            post2 = form.save()
            return redirect('notice_page')

    return render(request, 'main/notice_new.html',{
        'form': form,
    })

def notice_detail(request, post_id):
    post2 = Post2.objects.get(id=post_id)
    post_form2 = PostForm2()
    context = {
        'post2': post2,
        'post_form2': post_form2,
    }

    return render(request, 'main/notice_detail.html',context)

def notice_delete(request, post_id):
    post2 = get_object_or_404(Post2, id=post_id)
    post2.delete()   
    return redirect('notice_page')


# def univer (request,a_id):
#     t = University.objects.get(a_id =id)
#     return render(request, 'search_page',{'t':t})



def search_page(request,univers):
    # univer2 = University.objects.get(univer = chr(univers))
    customer_list = CustomUser.objects.filter( university = univers )


    search_type = request.GET.get('search_type','')       #검색 타입 받음
    search_keyword = request.GET.get('search_keyword','')  #검색 키워드 받음
    university = univers

    if search_keyword :   #검색 키워드가 있을 경우
        if len(search_keyword) > 1 :
            if search_type == '아이디':
                customer_list = customer_list.filter(username__icontains = search_keyword)
            elif search_type == '학교':
                customer_list = customer_list.filter(university__icontains = search_keyword)
            elif search_type == '학과':
                customer_list = customer_list.filter(major__icontains = search_keyword)
            elif search_type == '학번':
                customer_list = customer_list.filter(studentnumber__icontains = search_keyword)    
            elif search_type == '입시전형':

                customer_list = customer_list.filter(entrancetype__icontains = search_keyword)
        
        else :     #검색 키워드가 한글자인 경우
            messages.warning(request, "검색어는 2글자 이상 입력해주세요.")

    page = request.GET.get('page', '1')          #GET 방식으로 정보를 받아오는 데이터
    paginator = Paginator(customer_list, 5)      #Paginator(분할될 객체, 페이지 당 담길 객체수)
    page_obj = paginator.get_page(page)          #페이지 번호를 받아 해당 페이지를 리턴 get_page 권장

    context = {
        'search_keyword': search_keyword,
        'customer_list': customer_list,
        'search_type' : search_type,
        'university' : univers,
    }

    return render(request, 'main/search_page.html', context)

def search_pages(request):

    customer_list = CustomUser.objects.filter( mentor_check = True)  #멘토체크받은 리스트만 가져옴

    search_type = request.GET.get('search_type','')       #검색 타입 받음
    search_keyword = request.GET.get('search_keyword','')  #검색 키워드 받음

    if search_keyword :   #검색 키워드가 있을 경우
        if len(search_keyword) > 1 :
            if search_type == '아이디':
                customer_list = customer_list.filter(username__icontains = search_keyword)
            elif search_type == '학교':
                customer_list = customer_list.filter(university__icontains = search_keyword)
            elif search_type == '학과':
                customer_list = customer_list.filter(major__icontains = search_keyword)
            elif search_type == '학번':
                customer_list = customer_list.filter(studentnumber__icontains = search_keyword)    
            elif search_type == '입시전형':

                customer_list = customer_list.filter(entrancetype__icontains = search_keyword)
        
        else :     #검색 키워드가 한글자인 경우
            messages.warning(request, "검색어는 2글자 이상 입력해주세요.")


    page = request.GET.get('page', '1')          #GET 방식으로 정보를 받아오는 데이터
    paginator = Paginator(customer_list, 5)      #Paginator(분할될 객체, 페이지 당 담길 객체수)
    page_obj = paginator.get_page(page)          #페이지 번호를 받아 해당 페이지를 리턴 get_page 권장
    page_count = paginator.count                 #게시글 수를 page_count에 저장

    context = {
        'search_keyword': search_keyword,
        'customer_list': page_obj,
        'page_count': page_count,              
        'search_type' : search_type,
    }

    return render(request, 'main/search_pages.html', context)


def choice_mentor(request,customer_id): # 멘토들중 선택     
    mentor = CustomUser.objects.get(id =customer_id)    #선택한 id를 통해서 유저 정보를 가져온다
    Mentor.username = mentor.username   #가져온 유저 정보에서 정보를 requestform에 전달하기 위해 새로운 모델에 정보를 넣는다
    Mentor.email = mentor.email #이멜일 정보를 가져옴
    Mentor.university = mentor.university
    return redirect("requestform") #요청서 페이지로 넘어간다

def cat_1(request):
    return render(request, 'main/멘팅소개.html')

def cat_2(request):
    return render(request, 'main/모의고사일정.html')

def cat_3(request):
    return render(request, 'main/멘토만나기.html')

main/templates/main/comment_edit.html
{% extends 'accounts/base.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Community</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
    <link href="{% static 'css/community.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <div class="community_new_page">
        <h1>댓글 수정하기</h1>
        <br>
        <form action="{% url 'comment_edit' post.id comment.id %}" method="POST">
            {% if user.is_authenticated %}
            {% csrf_token %}

            <h6>작성자 : {{ user.username }}</h6>
            <h6>내용</h6>
            <h6>{{ form.content }}</h6>
            <br><br><br>
            <div class="button_locate">
                <input type="submit" value="작성" class="btn btn-outline-secondary">
                <button class="btn btn-outline-secondary"><a href="{% url 'community_detail' post.id %}"
                        class="link-dark">취소</a></button>
            </div>
            {% endif %}
        </form>
    </div>

    <footer>
        <div class="inner">
            <div class="info">
                <span>멋쟁이사자처럼 at 충북대학교 2조팀.</span>
            </div>

            <p class="copyright">
                &copy; <span class="this-year"></span> 2021 Menting Project
            </p>
        </div>
    </footer>
</body>

</html>
{% endblock content %}

main/templates/main/community_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>HOME</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="static/css/home.css" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/menubar.css' %}" rel="stylesheet">
</head>

<body>
    <div class="headerlogo">
      <a href="http://127.0.0.1:8000/"><img src="{% static 'img/멋사로고.png' %}" alt=""></a>
        {% if user.is_authenticated %}
        <div class="rightnav">
            <a class="nav-right" href="{% url 'logout' %}">로그아웃</a>
        </div>
        <div class="leftnav">
            <a class="nav-left" href="{% url 'mypage' %}">{{ user.username }}님의 my page</a>
        </div>
        {% endif %}
    </div>

    {% if user.is_authenticated %}
    <ul class="menu">

        <li class="menu-item"><a href="{% url 'search_pages' %}" class="menu-link">선배찾기</a></li>
        <li class="menu-item"><a href="{% url 'notice_page' %}" class="menu-link">공지사항</a></li>
        <li class="menu-item"><a href="{% url 'community_page' %}" class="menu-link">커뮤니티</a></li>

    </ul>
    {%else%}
    <ul class="menu">
        <li class="menu-item"><a href="http://127.0.0.1:8000/login/" class="menu-link">로그인</a></li>
        <li class="menu-item"><a href="http://127.0.0.1:8000/signup/" class="menu-link">회원가입</a></li>

        <li class="menu-item"><a href="http://127.0.0.1:8000/notice/" class="menu-link">공지사항</a></li>
        <li class="menu-item"><a href="http://127.0.0.1:8000/community/" class="menu-link">커뮤니티</a></li>
    </ul>
    {% endif %}
    <br> <br> <br>
    {% block content %}
    {% endblock content %}
</body>

</html>

main/templates/main/community_comment.html
<br>
<h1>댓글 쓰기</h1>

<form action="{% url 'community_comment' post.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type ="submit" class="btn btn-light" >생성</button>
    <button type="button" class="btn btn-light"><a href="{% url 'self_detail' post.id %}" class="link-dark">취소</a></button> 
</form>

main/templates/main/community_detail.html
{% extends 'accounts/base.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Community</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
    <link href="{% static 'css/community_detail.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&display=swap" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
</head>

<body>
    <div class="contant">
        <div class="community_detail">
            <br>
            <div class="container">
                <div class="card" id="contain1">
                    <div class="card-body">
                        <span class="post_title">{{ post.title }}</span>
                        <span class="post_user"><i class="fas fa-user-circle fa-lg" id="peopleicon"></i> {{ post.user}}<span
                                class="post_update">
                                {{post.updated_at}}</span></span>
                        <br><br>
                        <span class="post_content">{{ post.content }}</span>
                        <!-- {% if user.is_authenticated == True %}
                        <form action="{% url 'community_comment' post.id %}" method="POST">
                            {% csrf_token %}
                            <div class="form_community_detail"></div>
                            <textarea class="form-content" name="content" rows="2" cols="100"></textarea>
                            <input type="submit" value="작성" class="btn btn-outline-secondary btn-sm"> -->
                        <!-- <button class="btn btn-outline-secondary btn-sm"><a href="{% url 'community_detail' post.id %}"
                        class="link-dark">취소</a></button> -->
                    </div>
                    <!-- </form>
                    {% endif %} -->
                </div>
            </div>
            {% if user.is_authenticated == True %}
            <form action="{% url 'community_comment' post.id %}" method="POST" class="content_form">
                {% csrf_token %}
                <div class="form_community_detail"></div>
                <textarea class="form-content" name="content"></textarea>
                <input type="submit" value="작성" class="btn btn-outline-secondary btn-sm" id="comment_submit">
            </form>
            {% endif %}
        </div>
        <br><br>
        <span class="comment_list">댓글 목록</span>
        <br><br>
        {% for comment in post.comment_set.all %}
        <div class="container">
            <div class="card" id="contain2">
                <div class="card-body">
                    <i class="fas fa-user-circle" id="peopleicon"></i>
                    <p2 class="writer"> {{ comment.name }}</p2>
                    <br>
                    <p2 class="coment_content"> {{ comment.content }}</p2>
                    <br>
                    <p2 class="coment_update"> {{ comment.updated_at }} </p2>

                    {% if user.is_authenticated == True %}
                    <form action="{% url 'community_recomment' post.id comment.id %}" method="POST" class="commentform">
                        {% csrf_token %}
                        <textarea class="form-content2" name="content"></textarea>
                        <input type="submit" value="작성" class="btn btn-outline-secondary btn-sm" id="comment_submit2">
                    </form>
                    {% endif %}

                    <br><br>
                    {% for recomment in comment.recomment_set.all %}
                    <p2 class="writer2">┖> <i class="fas fa-user-circle" id="peopleicon2"></i>{{ recomment.name2 }}</p2>

                    <br>
                    <p2 class="recoment_content"> {{ recomment.content }} </p2>
                    <br>
                    <p2 class="recoment_update"> {{ recomment.updated_at }} </p2>

                    {% if user.is_authenticated and user.username == recomment.name2 %}
                    <button class="btn btn-outline-secondary btn-sm" id="delete_button"><a
                            href="{% url 'recomment_delete' post.id recomment.id %}" class="link-dark">삭제</a></button>
                    <hr>
                    {% endif %}
                    {% endfor %}

                    {% if user.is_authenticated and user.username == comment.name %}
                    <div class="userbutton">
                        <button class="btn btn-outline-secondary btn-sm" id="delete_button"><a
                                href="{% url 'comment_edit' post.id comment.id %}" class="link-dark">편집</a></button>
                        <button class="btn btn-outline-secondary btn-sm" id="delete_button"><a
                                href="{% url 'comment_delete' post.id comment.id %}" class="link-dark">댓글삭제</a></button>
                    </div>
                    {% endif %}
                </div>
            </div>
            <br>
        </div>
        {% endfor %}
        </div>

        <div class="community_end">
            <br>
            <button class="btn btn-outline-secondary btn-sm"><a href="{% url 'community_page' %}" class="link-dark">게시글
                    목록</a></button>
            {% if user.is_authenticated and user == post.user %}
            <button class="btn btn-outline-secondary btn-sm"><a href="{% url 'community_edit' post.id %}"
                    class="link-dark">게시글 수정</a></button>
            <button class="btn btn-outline-secondary btn-sm"><a href="{% url 'community_delete' post.id %}"
                    class="link-dark">게시글
                    삭제</a></button>
            <br><br><br>
            {% endif %}

        </div>
    </div>
    
    <footer>
        <div class="inner">
            <div class="info">
                <span>멋쟁이사자처럼 at 충북대학교 2조팀.</span>
            </div>

            <p class="copyright">
                &copy; <span class="this-year"></span> 2021 Menting Project
            </p>
        </div>
    </footer>
</body>

</html>
{% endblock content %}

main/templates/main/community_edit.html
{% extends 'accounts/base.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Community</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
    <link href="{% static 'css/community.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <div class="contant">
        <div class="community_edit_page">
            <h1>게시글 수정하기</h1>
            <br>
            <form action="{% url 'community_edit' post.id %}" method="POST">
                {% if user.is_authenticated %}
                {% csrf_token %}
                <h6>작성자 : {{ user.username }}</h6>
                <h6>제목</h6>
                <h6>{{ form.title }}</h6>
                <h6>내용</h6>
                <h6>{{ form.content }}</h6>

                <br>
                <div class="button_locate">
                    <input type="submit" value="작성" class="btn btn-outline-secondary btn-sm">
                    <a class="btn btn-outline-secondary btn-sm" href="{% url 'community_page' %}" role="button">취소</a>
                </div>
                {% endif %}
            </form>
        </div>
    </div>
    <footer>
        <div class="inner">
            <div class="info">
                <span>멋쟁이사자처럼 at 충북대학교 2조팀.</span>
            </div>

            <p class="copyright">
                &copy; <span class="this-year"></span> 2021 Menting Project
            </p>
        </div>
    </footer>
</body>

</html>
{% endblock content %}

main/templates/main/example_page.html
{% extends 'main/community_base.html' %}
{% load static %}
{% block content %}
<div class="notice_detail">
    <br>
    <h1>대학 : {{ custom.university }}</h1>
    <br>
</div>
<br>
<h1>같은학생</h1>
{% for customer in customer_list %}
    {% if customer.studenttype == True and customer.mentor_check == True and customer.university == custom.university %}
        <h1>학생 : {{ customer.username}}</h1> 
    {% endif %}
    {% endfor %}

{% endblock content %}

main/templates/main/notice_detail.html
{% extends 'accounts/base.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Notice</title>
    <link href="{% static 'css/common.css' %}" rel="stylesheet">
    <link href="{% static 'css/notice.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--Google Fonts - 나눔고딕-->
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
</head>

<body>
    <div class="contant">
        <div class="notice_detail">
            <br>

            <div class="container">
                <div class="card" id="contain">
                    <div class="card-body">
                        <span class="post_title">{{ post2.title }}</span>
                        <span class="post_user"><i class="fas fa-user-circle fa-lg" id="peopleicon"></i> STAFF<span
                                class="post_update">
                                {{post2.updated_at}}</span></span>
                        <br><br>
                        <span class="post_content">{{ post2.content }}</span>
                    </div>
                </div>
            </div>
        </div>

        <button class="btn btn-outline-secondary btn-sm" id="notice_button"><a href="{% url 'notice_page' %}"
                class="link-dark">목록</a></button>
        {% if user.is_superuser == True %}
        <button class="btn btn-outline-secondary btn-sm" id="notice_delete_button"><a
                href="{% url 'notice_delete' post2.id %}" class="link-dark">삭제</a></button>
        {% endif %}

    </div>
    <footer>
        <div class="inner">
            <div class="info">
                <span>멋쟁이사자처럼 at 충북대학교 2조팀.</span>
            </div>

            <p class="copyright">
                &copy; <span class="this-year"></span> 2021 Menting Project
            </p>
        </div>
    </footer>
</body>

</html>
{% endblock content %}

main/templates/main/universityname.html
<a href="{% url 'search_page' t.univer %}">
    <h1>{{t.univer}} 선배 보러가기 </h1>
</a>